---
title: "College Analysis"
output: 
  flexdashboard::flex_dashboard:
    social: [ "twitter", "github", "menu" ]
---

```{r setup, include=FALSE}
library(flexdashboard)
```

About {data-icon="fas fa-search" data-navmenu="Explore" }
===================================== 

Column {data-width=200}
-------------------------------------

### About this flexdashboard

This dashboard allows you to explore trends in house prices across 30 large metro areas. The metro areas covered are depicted in the nearby map.  The map is colored  according to Census regions.  We picked the 30 largest metro areas based on population. Explore the different data visualizations above.


Getting Our Data Ready {data-icon="fas fa-wrench"}
==============================================


Column 1 {data-width=400}
---------------------------------

### Getting Data

```{r, echo=TRUE, eval=FALSE}
library(rscorecard)
library(rstudioapi)
library(knitr)
library(dplyr)

# Key registration https://collegescorecard.ed.gov/data/documentation/
my_key <- askForPassword()
sc_key(my_key)


# Population predominantly bachelor's-degree granting colleges (preddeg==3)
df <- sc_init() %>% 
  sc_filter(preddeg==3) %>%
  sc_select(unitid, instnm, stabbr, city, actcm25, actcm75, ugds, control, distanceonly,
            md_earn_wne_p6, md_earn_wne_p8, md_earn_wne_p10,
            npt4_pub,npt4_priv, 
            omawdp8_ftft, 
            latitude,longitude) %>%
  sc_year('latest') %>% 
  sc_get()

# Exclusions 
# (1) Not online only (DISTANCEONLY == 0)
# (2) College in US state (exclude DC and US territories)

excluded_strabbr <- unique(df$stabbr[!df$stabbr %in% state.abb])
df <- df[df$stabbr %in% state.abb,]
df <- df[df$distanceonly == 0,]
save(df,"your file path")

```



## Column 2

### Our Data Sample

```{r, echo=TRUE}
load('college.Rda')
knitr::kable(head(df, n=8))
dim(df)
``` 

College Tuition {data-navmenu="Explore" data-icon="fas fa-university"} 
=================================================


### Setup 

```{r}
library(rscorecard)
library(rstudioapi)
library(knitr)
library(dplyr)
df$control <- factor(df$control, labels = c('public','private','for profit'))
df$npt <- df$npt4_priv
df$npt[is.na(df$npt)] <- df$npt4_pub[is.na(df$npt)]
df <- df %>% select(-c(npt4_priv,-npt4_pub))
df <- df[!is.na(df$npt),]
kable(df)
```





### Code





### Questions


